set hlsearch
syntax on
set langmenu=zh_CN
set imcmdline
set termencoding=utf8
set fileencodings=utf-8,gbk,ucs-bom,cp936
set tabstop=4
set ts=4
set smarttab
set expandtab
set sw=4
set number
set autoindent
